[project]
name = 'Tokenized-Sustainable-Agriculture-Certification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.certificate-issuance]
path = 'contracts/certificate-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.sustanability-assessment]
path = 'contracts/sustanability-assessment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
